version: '3'

volumes:
  postgres:
  node_modules:
  redis:

services:  
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    build: .
    command: rails s -b 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
    depends_on:
      - db
      - redis
    healthcheck:
      test: "exit 0"
  
  worker:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -d && bundle exec sidekiq -C /myapp/config/sidekiq.yml"
    volumes:
      - .:/myapp
    depends_on:
      web:
        condition: service_healthy

  redis:
    image: redis:6-alpine
    volumes:
      - "redis:/data"

