---
openapi: 3.0.1
info:
  title: Examinist API
  version: v1
  description: This is Examinist API documentation
paths: {}
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/
components:
  schemas:
    faculty:
      type: object
      properties:
        id:
          type: integer
        faculty_name:
          type: string
          example: Faculty of Engineering
        University_name:
          type: string
          example: Alexandria University
      required:
      - id
      - faculty_name
      - University_name
